// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitJoQnqMxb3PF92VpA1bjkxM7nLfFG70',
    appId: '1:859119700597:web:8d0af43ecffbd09deb863c',
    messagingSenderId: '859119700597',
    projectId: 'notifications-app-941d7',
    authDomain: 'notifications-app-941d7.firebaseapp.com',
    storageBucket: 'notifications-app-941d7.appspot.com',
    measurementId: 'G-DC8NTLE3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebZAifA5YufwqxEeNDx2KkEyOZa8nHQM',
    appId: '1:859119700597:android:8f3ab4be0aee08f7eb863c',
    messagingSenderId: '859119700597',
    projectId: 'notifications-app-941d7',
    storageBucket: 'notifications-app-941d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Q7mj6KoP4u_pmsit9_BM0nSJF_S6u_w',
    appId: '1:859119700597:ios:aabd64a5c8b8379feb863c',
    messagingSenderId: '859119700597',
    projectId: 'notifications-app-941d7',
    storageBucket: 'notifications-app-941d7.appspot.com',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1Q7mj6KoP4u_pmsit9_BM0nSJF_S6u_w',
    appId: '1:859119700597:ios:aabd64a5c8b8379feb863c',
    messagingSenderId: '859119700597',
    projectId: 'notifications-app-941d7',
    storageBucket: 'notifications-app-941d7.appspot.com',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAitJoQnqMxb3PF92VpA1bjkxM7nLfFG70',
    appId: '1:859119700597:web:a607cff47ff492bceb863c',
    messagingSenderId: '859119700597',
    projectId: 'notifications-app-941d7',
    authDomain: 'notifications-app-941d7.firebaseapp.com',
    storageBucket: 'notifications-app-941d7.appspot.com',
    measurementId: 'G-RRZ03884DR',
  );
}
